name: flakehub publish

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: install nix
        uses: nixbuild/nix-quick-install-action@v26

      - name: push to flakehub
        uses: DeterminateSystems/flakehub-push@v3
        with:
          visibility: "public"
          rolling: true
