name: Auto-merge staging

on:
  push:
    branches: ["staging"]
  workflow_dispatch:

jobs:
  automerge:
    name: Auto-merge
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR exists
        id: check
        run: |
          prs=$(gh pr list \
            --repo ${{ github.repository }} \
            --head staging \
            --json state \
            --jq 'map(select(.state == "OPEN")) | length')

          if (( prs > 0 )); then
            echo "skip=true" >> "$GITHUB_OUTPUT"
          fi

        env:
          GH_TOKEN: ${{ github.token }}

      - uses: actions/checkout@v4
        if: ${{ !steps.check.outputs.skip }}
        with:
          fetch-depth: 0

      - name: Create PR
        if: ${{ !steps.check.outputs.skip }}
        run: |
          gh pr create \
            --base main \
            --head ${{ github.ref_name }} \
            --title "auto-merge: ${{ github.ref_name }} -> main" \
            --fill
        env:
          GH_TOKEN: ${{ secrets.MERGE_TOKEN }}

      - name: Enable auto-merge
        if: ${{ !steps.check.outputs.skip }}
        run: gh pr merge --auto --rebase --match-head-commit ${{ github.sha }}
        env:
          GH_TOKEN: ${{ secrets.MERGE_TOKEN }}
