name: auto-merge staging

on:
  push:
    branches: ["staging"]
  workflow_dispatch:

jobs:
  automerge:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: create pr
        run: |
            gh pr create \
              --base main \
              --head ${{ github.ref_name }} \
              --title "auto-merge: ${{ github.ref_name }} -> main" \
              --fill
        env:
          GITHUB_TOKEN: ${{ github.token }}


      - name: enable auto-merge
        run: gh pr merge --auto --rebase --match-head-commit ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
