name: auto-merge staging

on:
  push:
    branches: ["staging"]
  workflow_dispatch:

jobs:
  automerge:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: create pr
        run: |
          {
            echo 'PR<<EOF'
            gh pr create \
              --repo ${{ github.repository }} \
              --base main \
              --head ${{ github.ref_name }} \
              --title "auto-merge: ${{ github.ref_name }} -> main" \
              --fill
            echo EOF
          } >> "$GITHUB_ENV"

        env:
          GITHUB_TOKEN: ${{ github.token }}


      - name: enable auto-merge
        run: gh pr merge --auto --rebase "$PR"
        env:
          GITHUB_TOKEN: ${{ github.token }}
